### ISSUE TITLE
web load balancer type.

### ISSUE THREAD

**Issue by khabbabs** [pivotal-cf/terraforming-aws#119]
Reading the docs on installing pivotal `[manually on aws](https://docs.pivotal.io/pivotalcf/2-4/om/aws/prepare-env-manual.html#pcfaws-web-lb)`  step 13 says to create an application load balancer while terraform code creates an network type load balancer. 

Which method is correct? 

https://github.com/pivotal-cf/terraforming-aws/blob/9a47766dc276d489ff6bb23ae8357b874e7dd625/modules/pas/lbs.tf#L34

**Comment by nmahoney-pivotal** [comment]
An updated AWS reference architecture is still in the process of being added to the docs, but it recommends Network Load Balancers. So I would say that the manual docs should probably be updated.

**Comment by nmahoney-pivotal** [comment]
This does require adding custom `vm_extensions`, since the `Load Balancers` field on the `Resource Config` page of Ops Manager only creates a `vm_extension` for the target group and not the security group. This is because NLBs themselves can't be added to security groups. I'm not sure if this is the case for ALBs. ELBs could be added to security groups, which is why Ops Manager works the way it does. Anyway, these commands should add those `vm_extensions` for you:
```
om -k create-vm-extension \
--name "web-lb-security-groups" \
--cloud-properties '{ "security_groups": ["web_lb_security_group"], "target_groups":["web-lb-target-groups"] }'

om -k create-vm-extension \
--name "ssh-lb-security-groups" \
--cloud-properties '{ "security_groups": ["ssh_lb_security_group"], "target_groups":["ssh-lb-target-groups"] }'

om -k create-vm-extension \
--name "tcp-lb-security-groups" \
--cloud-properties '{ "security_groups": ["tcp_lb_security_group"], "target_groups":["tcp-lb-target-groups"] }'
```

I'm currently in the process of adding this to the docs and testing it.

**Comment by nmahoney-pivotal** [comment]
You might need to add `vms_security_group` to all three security group lists, i.e.
```
om -k create-vm-extension \
--name "web-lb-security-groups" \
--cloud-properties '{ "security_groups": ["web_lb_security_group", "vms_security_group"], "target_groups":["web-lb-target-groups"] }'

om -k create-vm-extension \
--name "ssh-lb-security-groups" \
--cloud-properties '{ "security_groups": ["ssh_lb_security_group", "vms_security_group"], "target_groups":["ssh-lb-target-groups"] }'

om -k create-vm-extension \
--name "tcp-lb-security-groups" \
--cloud-properties '{ "security_groups": ["tcp_lb_security_group", "vms_security_group"], "target_groups":["tcp-lb-target-groups"] }'
```
