### ISSUE TITLE
README is not clear about whether or not user can create more than 1 RDS

### ISSUE THREAD

**Issue by ArseniiPetrovich** [pivotal-cf/terraforming-aws#147]
If so, the output of the RDS module will throw info about the very first created RDS:
```
"${element(concat(aws_db_instance.rds.*.address, list("")), 0)}"
```

**Comment by genevieve** [comment]
Hi @ArseniiPetrovich. We expect users to either have no RDS instance or one RDS instance. When any resource has a `count` property (which it will need so it can be set to `0` or `1`), we need to use the terraform interpolation syntax that you pasted above so that we _if_ there is an RDS instance, _then_ we get the address of the first (and only) RDS instance.
