### ISSUE TITLE
Output has ops_manager_ssh_private_key as sensitive

### ISSUE THREAD

**Issue by ShawnTuatara** [pivotal-cf/terraforming-aws#44]
Following the guide at:

https://docs.pivotal.io/pivotalcf/2-1/customizing/aws-om-config-terraform.html#aws-config

It says to look at the terraform output for the value of `ops_manager_ssh_private_key`. In a recent commit that output has been marked as sensitive so people reading the guide can't complete that step.

https://github.com/pivotal-cf/terraforming-aws/blob/master/outputs.tf#L170

Manually removing the sensitive flag on that output.tf file and re-running `terraform refresh` shows the private key and allows for the completion of the guide.

**Comment by genevieve** [comment]
If you run `terraform output` you will see the value of that key. What `sensitive` does is keep that output from being displayed during normal commands like `apply` or `destroy` so that it doesn't get exposed on a regular basis. Instead you have to explicitly call `terraform output` to show the value. We can make a PR to the documentation to tell the user to run that command.
